-- Nuxt Movie Booking schema (Oracle)
-- Run against the app schema (movie_app) after the database is up.

CREATE TABLE theaters (
  id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  city VARCHAR2(100) NOT NULL
);

CREATE TABLE movies (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title            VARCHAR2(200) NOT NULL,
  genre            VARCHAR2(50) NOT NULL,
  duration_minutes NUMBER NOT NULL,
  poster_url       VARCHAR2(500),
  is_trending      NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE showtimes (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id    NUMBER NOT NULL REFERENCES movies(id),
  theater_id  NUMBER NOT NULL REFERENCES theaters(id),
  hall_name   VARCHAR2(50) NOT NULL,
  starts_at   TIMESTAMP NOT NULL,
  price       NUMBER NOT NULL,
  seat_count  NUMBER DEFAULT 50 NOT NULL
);

CREATE TABLE customers (
  id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  VARCHAR2(200) NOT NULL,
  email VARCHAR2(200) NOT NULL UNIQUE
);

CREATE TABLE bookings (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  showtime_id   NUMBER NOT NULL REFERENCES showtimes(id),
  customer_id   NUMBER NOT NULL REFERENCES customers(id),
  seat_number   VARCHAR2(10) NOT NULL,
  booked_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_seat_per_showtime UNIQUE (showtime_id, seat_number)
);

CREATE TABLE promotions (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       VARCHAR2(200) NOT NULL,
  description VARCHAR2(500) NOT NULL,
  image_url   VARCHAR2(500)
);

-- Starter theaters
INSERT INTO theaters (name, city) VALUES ('Downtown Multiplex', 'Bangkok');
INSERT INTO theaters (name, city) VALUES ('Riverside Cinema', 'Bangkok');
INSERT INTO theaters (name, city) VALUES ('Grand Galaxy Theater', 'Nonthaburi');

-- Starter movies
INSERT INTO movies (title, genre, duration_minutes, is_trending) VALUES ('The Last Signal', 'Sci-Fi', 128, 1);
INSERT INTO movies (title, genre, duration_minutes, is_trending) VALUES ('Midnight Bakery', 'Comedy', 102, 0);
INSERT INTO movies (title, genre, duration_minutes, is_trending) VALUES ('Iron Coast', 'Action', 141, 1);

-- Starter showtimes: each movie plays across all 3 theaters
INSERT INTO showtimes (movie_id, theater_id, hall_name, starts_at, price) VALUES (1, 1, 'Hall 1', TIMESTAMP '2026-09-19 11:30:00', 220);
INSERT INTO showtimes (movie_id, theater_id, hall_name, starts_at, price) VALUES (1, 1, 'Hall 1', TIMESTAMP '2026-09-19 14:15:00', 220);
INSERT INTO showtimes (movie_id, theater_id, hall_name, starts_at, price) VALUES (1, 2, 'Hall A', TIMESTAMP '2026-09-19 16:20:00', 220);
INSERT INTO showtimes (movie_id, theater_id, hall_name, starts_at, price) VALUES (1, 3, 'Hall 1', TIMESTAMP '2026-09-19 20:00:00', 240);

INSERT INTO showtimes (movie_id, theater_id, hall_name, starts_at, price) VALUES (2, 1, 'Hall 2', TIMESTAMP '2026-09-19 15:00:00', 180);
INSERT INTO showtimes (movie_id, theater_id, hall_name, starts_at, price) VALUES (2, 2, 'Hall 2', TIMESTAMP '2026-09-19 12:00:00', 180);
INSERT INTO showtimes (movie_id, theater_id, hall_name, starts_at, price) VALUES (2, 3, 'Hall 2', TIMESTAMP '2026-09-19 18:30:00', 190);

INSERT INTO showtimes (movie_id, theater_id, hall_name, starts_at, price) VALUES (3, 1, 'Hall 3', TIMESTAMP '2026-09-19 21:00:00', 260);
INSERT INTO showtimes (movie_id, theater_id, hall_name, starts_at, price) VALUES (3, 2, 'Hall B', TIMESTAMP '2026-09-19 17:40:00', 250);
INSERT INTO showtimes (movie_id, theater_id, hall_name, starts_at, price) VALUES (3, 3, 'Hall 3', TIMESTAMP '2026-09-19 13:00:00', 250);

-- Starter promotions
INSERT INTO promotions (title, description) VALUES ('Combo Deal', 'Large popcorn + 2 soft drinks for only $8.99 — save 30% at the counter.');
INSERT INTO promotions (title, description) VALUES ('Student Tuesday', 'Show a student ID on Tuesdays for 20% off any showtime.');

COMMIT;
