-- Nuxt Movie Booking schema (Oracle)
-- Run against the app schema (movie_app) after the database is up.

CREATE TABLE movies (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title            VARCHAR2(200) NOT NULL,
  genre            VARCHAR2(50) NOT NULL,
  duration_minutes NUMBER NOT NULL,
  poster_url       VARCHAR2(500)
);

CREATE TABLE showtimes (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id    NUMBER NOT NULL REFERENCES movies(id),
  hall_name   VARCHAR2(50) NOT NULL,
  starts_at   TIMESTAMP NOT NULL,
  price       NUMBER NOT NULL,
  seat_count  NUMBER DEFAULT 50 NOT NULL
);

CREATE TABLE bookings (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  showtime_id   NUMBER NOT NULL REFERENCES showtimes(id),
  customer_name VARCHAR2(200) NOT NULL,
  seat_number   VARCHAR2(10) NOT NULL,
  booked_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_seat_per_showtime UNIQUE (showtime_id, seat_number)
);

-- Starter movies + showtimes
INSERT INTO movies (title, genre, duration_minutes) VALUES ('The Last Signal', 'Sci-Fi', 128);
INSERT INTO movies (title, genre, duration_minutes) VALUES ('Midnight Bakery', 'Comedy', 102);
INSERT INTO movies (title, genre, duration_minutes) VALUES ('Iron Coast', 'Action', 141);

INSERT INTO showtimes (movie_id, hall_name, starts_at, price) VALUES (1, 'Hall 1', TIMESTAMP '2026-09-19 18:30:00', 220);
INSERT INTO showtimes (movie_id, hall_name, starts_at, price) VALUES (1, 'Hall 1', TIMESTAMP '2026-09-19 21:15:00', 220);
INSERT INTO showtimes (movie_id, hall_name, starts_at, price) VALUES (2, 'Hall 2', TIMESTAMP '2026-09-19 19:00:00', 180);
INSERT INTO showtimes (movie_id, hall_name, starts_at, price) VALUES (3, 'Hall 3', TIMESTAMP '2026-09-19 20:00:00', 250);

COMMIT;
